// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrpy8SVF6AEg-gjJ5uGjyYtybc2APsUUc',
    appId: '1:927665559732:web:ac5715b5a84f946f325fe1',
    messagingSenderId: '927665559732',
    projectId: 'myblog-8ca17',
    authDomain: 'myblog-8ca17.firebaseapp.com',
    databaseURL: 'https://myblog-8ca17-default-rtdb.firebaseio.com',
    storageBucket: 'myblog-8ca17.firebasestorage.app',
    measurementId: 'G-4NB18PWJXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsXGfTNAXz1CxWddmeaZWtDyCGFv8yK7o',
    appId: '1:927665559732:android:853addd3bc7720b1325fe1',
    messagingSenderId: '927665559732',
    projectId: 'myblog-8ca17',
    databaseURL: 'https://myblog-8ca17-default-rtdb.firebaseio.com',
    storageBucket: 'myblog-8ca17.firebasestorage.app',
  );

}