// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIYTuQnno1qb7WF_GD1jiKq_580pqRXI',
    appId: '1:880431422459:web:22c3ed68f382bdf800c95e',
    messagingSenderId: '880431422459',
    projectId: 'fire-app-8408a',
    authDomain: 'fire-app-8408a.firebaseapp.com',
    databaseURL: 'https://fire-app-8408a-default-rtdb.firebaseio.com',
    storageBucket: 'fire-app-8408a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHBa37nXaO1Qj5CrrF67_qRTfP_RH3_oQ',
    appId: '1:880431422459:android:39803773df8d8a7f00c95e',
    messagingSenderId: '880431422459',
    projectId: 'fire-app-8408a',
    databaseURL: 'https://fire-app-8408a-default-rtdb.firebaseio.com',
    storageBucket: 'fire-app-8408a.firebasestorage.app',
  );
}
